# Generated by Django 2.2.3 on 2020-04-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200402_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Office'),
        ),
    ]
