# Generated by Django 2.2.3 on 2020-03-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20200330_0836'),
        ('lb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='currently_quarantined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipality',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='public.Person'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair', to='public.Person'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='deputy_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_chair', to='public.Person'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lb.District'),
        ),
        migrations.AddField(
            model_name='qtperson',
            name='remarks',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_quarantine',
            field=models.IntegerField(default=1),
        ),
    ]
