# Generated by Django 2.2.3 on 2020-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_auto_20200402_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidcases',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
