# Generated by Django 2.2.3 on 2020-04-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0006_office_relieffund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relieffund',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lb.Office'),
        ),
    ]
