# Generated by Django 2.2.3 on 2020-04-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0007_auto_20200403_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Person2')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Office')),
            ],
        ),
    ]
