# Generated by Django 2.2.3 on 2020-04-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20200407_0848'),
        ('lb', '0009_reliefitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relieffund',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relieffund',
            name='relief_details',
        ),
        migrations.AddField(
            model_name='person2',
            name='formtype',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reliefitem',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='public.Person'),
        ),
    ]
