# Generated by Django 2.2.3 on 2020-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0010_auto_20200409_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='उमेर'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='current_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='अस्थाई ठेगाना'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='पुरा नाम'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='mobile',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='मोबाइल नं'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='स्थाई ठेगाना'),
        ),
    ]
