# Generated by Django 2.2.3 on 2020-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0011_auto_20200411_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
