# Generated by Django 2.2.3 on 2020-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0012_auto_20200413_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
