# Generated by Django 2.2.3 on 2020-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0013_auto_20200413_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ward',
            field=models.CharField(blank=True, default=1, max_length=30, null=True),
        ),
    ]
