# Generated by Django 2.2.3 on 2020-04-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0014_auto_20200414_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliefitem',
            name='food_type',
        ),
    ]
