# Generated by Django 2.2.3 on 2020-03-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=300, null=True)),
                ('ward', models.IntegerField(default=1)),
                ('mun', models.CharField(max_length=300)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('District', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full Name', models.CharField(max_length=300)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('current_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Temporary', to='public.Address')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permanent', to='public.Address')),
            ],
        ),
    ]
