# Generated by Django 2.2.3 on 2020-03-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20200330_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_need', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Person')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='public.Person')),
            ],
        ),
    ]
