# Generated by Django 2.2.3 on 2020-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_person_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Full Name',
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default=0, max_length=300, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
