# Generated by Django 2.2.3 on 2020-03-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20200330_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Age',
            new_name='age',
        ),
    ]
