# Generated by Django 2.2.3 on 2020-04-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20200401_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_full_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Temporary', to='public.Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='permanent_full_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permanent', to='public.Address'),
        ),
    ]
