# Generated by Django 2.2.3 on 2020-04-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_auto_20200402_0016'),
        ('form', '0005_auto_20200402_0016'),
        ('food_meds', '0005_auto_20200402_0016'),
        ('public', '0009_auto_20200401_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_full_address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='permanent_full_address',
        ),
        migrations.AlterField(
            model_name='family',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Person'),
        ),
        migrations.AlterField(
            model_name='family',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='lb.Person'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Person'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
