# Generated by Django 2.2.3 on 2020-04-02 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_auto_20200402_0055'),
        ('public', '0009_auto_20200401_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_postive', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, max_length=300, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='current_full_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Temporary', to='lb.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='permanent_full_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permanent', to='lb.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='qtperson',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Person'),
        ),
        migrations.AddField(
            model_name='qtperson',
            name='quarantined_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lb.Hospital'),
        ),
    ]
