# Generated by Django 2.2.3 on 2020-04-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20200402_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='relation_type',
            field=models.IntegerField(default=0),
        ),
    ]
