# Generated by Django 2.2.3 on 2020-04-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_family_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='belong_to_form',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('mobile', 'belong_to_form')},
        ),
    ]
