# Generated by Django 2.2.3 on 2020-04-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20200403_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='लिङ्ग'),
        ),
    ]
