# Generated by Django 2.2.3 on 2020-04-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20200407_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtperson',
            old_name='is_postive',
            new_name='is_positive',
        ),
    ]
