# Generated by Django 2.2.3 on 2020-03-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0002_auto_20200330_0836'),
        ('public', '0003_auto_20200330_0836'),
        ('food_meds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('qty', models.FloatField(default=0.0)),
                ('qty_unit', models.CharField(max_length=300)),
                ('sufficiency', models.IntegerField(default=1)),
                ('ordered_by', models.IntegerField()),
                ('order_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type_medicine', models.CharField(max_length=150)),
                ('qty', models.CharField(max_length=400)),
                ('sufficiency', models.IntegerField(default=1)),
                ('ordered_by', models.IntegerField()),
                ('order_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('qty', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('produced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Petroleum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('qty', models.CharField(max_length=400)),
                ('sufficiency', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('demand_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('required_qty', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('available', models.CharField(max_length=50)),
                ('produced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_delivery', models.IntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Person')),
            ],
        ),
    ]
