# Generated by Django 2.2.3 on 2020-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0002_delivery_food_medical_medicine_petroleum_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
