# Generated by Django 2.2.3 on 2020-04-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0004_auto_20200401_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Person'),
        ),
    ]
