# Generated by Django 2.2.3 on 2020-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0004_auto_20200401_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='petroleum',
            name='qty_unit',
            field=models.CharField(default='वटा', max_length=160),
        ),
        migrations.AddField(
            model_name='production',
            name='produce_freq',
            field=models.CharField(default='daily', max_length=50),
        ),
    ]
