# Generated by Django 2.2.3 on 2020-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0009_auto_20200409_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='qty_unit',
            field=models.CharField(default='केजी', max_length=80),
        ),
        migrations.AddField(
            model_name='production',
            name='qty_unit',
            field=models.CharField(default='केजी', max_length=70),
        ),
        migrations.AlterField(
            model_name='medical',
            name='available',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='produce_freq',
            field=models.CharField(blank=True, default='daily', max_length=50, null=True),
        ),
    ]
