# Generated by Django 2.2.3 on 2020-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0010_auto_20200412_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='sufficiency',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
