# Generated by Django 2.2.3 on 2020-04-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_meds', '0011_auto_20200414_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodname',
            name='qty',
            field=models.CharField(default='1', max_length=30, verbose_name='परिमाण'),
        ),
    ]
