# Generated by Django 2.2.3 on 2020-04-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('food_meds', '0012_foodname_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorldProcess',
        ),
    ]
