# Generated by Django 2.2.3 on 2020-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival Date', models.DateField(blank=True, null=True, verbose_name='Nepal Arrival Date by Air')),
                ('Foreign Country', models.CharField(max_length=300, verbose_name='Outside Country')),
                ('mode_of_transport', models.CharField(max_length=100)),
            ],
        ),
    ]
