# Generated by Django 2.2.3 on 2020-03-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='mode_of_transport',
        ),
        migrations.AddField(
            model_name='travel',
            name='mode_of_transport_international',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='विदेशवाट नेपाल प्रवेश गर्दा प्रयोग गरेको यातायात साधन'),
        ),
        migrations.AddField(
            model_name='travel',
            name='mode_of_transport_national',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='काठमाडौँ वा नाकावाट स्थानिय तहमा आउदा प्रयोग गरेको यातायात साधन'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Arrival Date',
            field=models.DateField(blank=True, null=True, verbose_name='नेपाल प्रवेश मिति'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Foreign Country',
            field=models.CharField(max_length=300, verbose_name='बाहिर रहेको देश'),
        ),
    ]
