# Generated by Django 2.2.3 on 2020-03-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20200330_0836'),
        ('form', '0002_auto_20200330_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='traveller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='public.Person'),
            preserve_default=False,
        ),
    ]
