# Generated by Django 2.2.3 on 2020-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_travel_traveller'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
