# Generated by Django 2.2.3 on 2020-04-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_travel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Person'),
        ),
    ]
