# Generated by Django 2.2.3 on 2020-04-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_travel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
