# Generated by Django 2.2.3 on 2020-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_travel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='Arrival Date',
            field=models.TextField(blank=True, null=True, verbose_name='नेपाल प्रवेश मिति'),
        ),
    ]
