# Generated by Django 2.2.3 on 2020-04-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0011_auto_20200411_1105'),
        ('form', '0008_stat_statvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lb.Office'),
        ),
        migrations.CreateModel(
            name='StatCounters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('class_name', models.CharField(max_length=300)),
                ('constraint', models.CharField(max_length=100)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Stat')),
            ],
        ),
    ]
