# Generated by Django 2.2.3 on 2020-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20200413_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidcounters',
            name='cured',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='निको भएको'),
        ),
        migrations.AlterField(
            model_name='covidcounters',
            name='death',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='मृत्यु'),
        ),
        migrations.AlterField(
            model_name='covidcounters',
            name='infected',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='सङ्क्रमित'),
        ),
        migrations.AlterField(
            model_name='covidcounters',
            name='result_waiting',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='नतिजा आउन बाँकी'),
        ),
        migrations.AlterField(
            model_name='covidcounters',
            name='samples',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='सङ्कलित नमुना'),
        ),
    ]
