# Generated by Django 2.2.3 on 2020-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_auto_20200423_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Tabular Reports'},
        ),
        migrations.AddField(
            model_name='dashfields',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
