# Generated by Django 2.2.3 on 2020-05-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0015_remove_reliefitem_food_type'),
        ('form', '0016_auto_20200423_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_size', models.CharField(max_length=400)),
                ('table_name', models.CharField(max_length=300)),
                ('mun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Municipality')),
            ],
        ),
    ]
