# Generated by Django 2.2.3 on 2020-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_columnsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnsize',
            name='column_size',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
